### ISSUE TITLE
tests do not run...

### ISSUE THREAD

**Issue by busticated** [saschajullmann/gatsby-starter-gatsbythemes#1]
**Repro Steps:**

1. `gatsby new my-project https://github.com/saschajullmann/gatsby-starter-gatsbythemes`
2. `cd my-project`
3. `npm test`

**Expected:**
tests run and pass

**Actual:**

     FAIL  src/components/Footer/footer.test.js
     ● Test suite failed to run

     /my-project/src/components/Footer/footer.test.js: Unexpected token (8:23)
             6 | 
             7 | it('renders correctly', () => {
          >  8 |   const tree = shallow(<Footer />);
               |                        ^
             9 |   expect(toJson(tree)).toMatchSnapshot();
            10 | });
            11 | 

     Test Suites: 1 failed, 1 total
     Tests:       0 total
     Snapshots:   0 total
     Time:        1.422s

**Comment by macklinu** [comment]
I can't reproduce this locally. Perhaps a newer version of Gatsby resolved this? Not really sure 🤷‍♂️

**Comment by saschajullmann** [comment]
Sorry for the late response.

I also can't reproduce this locally. Both "yarn run test" and "npm test" will both run the test successfully. Which OS are you using?

**Comment by saschajullmann** [comment]
@markmssd could you maybe try to clone the repo, cd into it and install the npm packages (either "yarn install" or "npm install") and after that try to run the tests.

**Comment by ThiagoMiranda** [comment]
I had this issue when I configured a project without the .babelrc file. Jest depends on it to interpret the JSX syntax. 
But now I´m having this error:
` TypeError: Cannot read property 'ReactCurrentOwner' of undefined`
Has anyone experienced it?

Thanks

**Comment by markmssd** [comment]
I think I had this error when testing with Enzyme, and that your Enzyme adapter is not the correct version for the ReactJS version.

**Comment by i001962** [comment]
Same error here. This is what I did to get around it:
npm i --save react@16 react-dom@16
npm i --save-dev enzyme enzyme-adapter-react-16

**Comment by saschajullmann** [comment]
Thanks @i001962 for the hint. Those dependencies are actually in the package, I'm not quite sure why they wouldn't be installed when you use it.

So when someone else encounters this problem I suggest removing the node_modules folder and reinstall the dependencies (yarn install/ npm install).
