### ISSUE TITLE
FYI -had to add rel="noopener noreferrer"

### ISSUE THREAD

**Issue by jholowicki** [saschajullmann/gatsby-starter-gatsbythemes#4]
When I hit 'gatsby develop', it threw an error:
`  117:19  error  Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener  react/jsx-no-target-blank
`
So I replaced  rel="noopener" with rel="noopener noreferrer",  and that replacement removed the error.

I'm going to try to submit a pull request!

**Comment by saschajullmann** [comment]
Awesome, thank you very much for catching this!
